name: Terraform Backend Setup

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "backend-setup/**", ".github/workflows/backend-aks.yml" ]

permissions:
  id-token: write
  contents: read

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Init & Apply backend
        working-directory: backend-setup
        env:
          TF_VAR_location: ${{ vars.AZURE_LOCATION }} # e.g. eastus
          TF_VAR_project: ${{ vars.PROJECT_NAME }}    # e.g. revinci
        run: |
          terraform init -upgrade
          terraform apply -auto-approve                 -var "location=${TF_VAR_location}"                 -var "project=${TF_VAR_project}"

      - name: Show outputs
        working-directory: backend-setup
        run: terraform output -json
