name: Deploy AKS Infra

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "terraform-aks/**"
      - "environments/**"
      - ".github/workflows/deploy-aks.yml"

permissions:
  id-token: write
  contents: read

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev # override via workflow dispatch input if desired
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (Remote State)
        working-directory: terraform-aks
        run: terraform init -upgrade

      - name: Terraform Validate
        working-directory: terraform-aks
        run: |
          terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file="environments/${{ github.event.inputs.env }}.tfvars" -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
